### ISSUE TITLE
oar-node init script not always working because of an order issue

### ISSUE THREAD

**Issue by bzizou** [oar-team/oar#15] opened 2015-01-29 16:03 UTC
The oar-node startup script may trig the following error:

"Starting OAR node: Missing privilege separation directory: /var/run/sshd"

The following patch solves the issue (need to launch 'update_rc.d oar-node enable' to update the init scripts links)

--- /etc/init.d/oar-node        2015-01-26 21:13:18.000000000 +0100
+++ oar-node    2015-01-29 16:51:28.040187620 +0100
@@ -7,7 +7,7 @@
 #
 ### BEGIN INIT INFO
 # Provides:         oar-node
-# Required-Start:   $network $local_fs $remote_fs
+# Required-Start:   $network $local_fs $remote_fs sshd
 # Required-Stop:    $network $local_fs $remote_fs
 # Default-Start:    2 3 4 5
 # Default-Stop:     0 1 6

**Comment by npf** [comment] 2015-02-01 21:40
I did not reproduce the bug in oar-vagrant... Could you try ?
For the fix,we could also just create the /var/run/sshd directory...

**Comment by npf** [comment] 2015-02-06 22:40
I indeed reproduced the bug on Debain Wheezy, but not on Jessie, nor in Centos6.

On Wheezy indeed, oar-node service currently gets a higher/earlier start priority than ssh, which explain the issue.

On Jessie, oar-node also gets a higher/earlier start priority in rc.d/.., but it has not effect, first of all because sshd is actually started from elsewhere, as a native systemd service. But removing ssh service using update-rc.d does not cause the issue to appear, nor does preventing the systemd ssh service to run on boot, by creating the /etc/ssh/sshd_not_to_be_run file (see /etc/systemd/system/sshd.service). Removing /var/run/sshd by hand and restarting oar-node shows the error however.
 Jessie's boot at /var/run mount time seems to actually make sure /var/run/sshd exists in any case.

On Centos6, priority of oar-node is lower/later than sshd.

My proposal is to fix the issue in the wheezy backport package, debian version 2.5.4-2~bpo70+1 when we will release it, but not touch 2.5.4-2.

**Comment by npf** [comment] 2015-02-24 10:39
This is to be fixed in the wheezy backport package, branch debian/2.5_bpo70, by adding a mkdir -p /var/run/sshd to the oar-node init-script.

**Comment by npf** [comment] 2015-04-10 10:40
fixed in Debian package 2.5.4-2 (patch)

**Closed by npf** 2015-04-10 10:40 UTC
Labels: bug, debian
