### ISSUE TITLE
Oaradmissionrules - Activate new rule fail with DBD::mysql::db do failed: You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by clement-parisot** [oar-team/oar#53] opened 2015-07-17 11:09 UTC
Hello,
I tried to add a new admission rule in OAR 2.5.4 using mysql database.
The command I used is : 

    oaradmissionrules -n

I typed:

    if ($queue_name ne "production"){
     if ($jobproperties ne ""){
      $jobproperties = "($jobproperties) AND production = 'NO'";
     }else{
      $jobproperties = "production = 'NO'";
     }
    }else{
     if ($jobproperties ne ""){
      $jobproperties = "($jobproperties) AND production = 'YES'";
     }else{
      $jobproperties = "production = 'YES'";
     }
    }

But command failed with this error:

    DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(priority, enabled, rule) = (0, 'YES', 'if ($queue_name ne \"production\"){\n if' at line 2 at /usr/share/perl5/OAR/IO.pm line 4785.

I tried to change the rule and add some escaped characters (like \' or \") but there is allways the same error. I tried to import it from a file but it didn't change anything.

Is there a bug in OAR or syntax of the new rule is incorrect ?
Best regards,
Clement

**Comment by npf** [comment] 2015-07-17 14:45
I just tested with both postgresql and mysql using the exact code above (copy-paste), and I could not reproduce the error.

**Comment by clement-parisot** [comment] 2015-07-17 14:54
The bug appears when you activate the rule (oaradmissionrules -m #Rule number -Y) or when you edit it.
I successfully added the new rules directly in mysql with the following syntax

```sql
# Force production ressource to be used or not
INSERT IGNORE INTO admission_rules (rule) VALUES ('
if ($queue_name ne "production"){
 if ($jobproperties ne ""){
  $jobproperties = "($jobproperties) AND production = \\\'NO\\\'";
 }else{
  $jobproperties = "production = \\\'NO\\\'";
 }
}else{
 print("[ADMISSION RULE] Added automatically production resource constraints\\n");
 if ($jobproperties ne ""){
  $jobproperties = "($jobproperties) AND production = \\\'YES\\\'";
 }else{
  $jobproperties = "production = \\\'YES\\\'";
 }
}
');
```
oaradmissinrules show the rule like this:

    root@taurus-1:~# oaradmissionrules -s 10 -f
    --- (0) RULE # 10
    
    if ($queue_name ne "production"){
     if ($jobproperties ne ""){
      $jobproperties = "($jobproperties) AND production = \'NO\'"; 
     }else{
      $jobproperties = "production = \'NO\'"; 
     }
    }else{
     print("[ADMISSION RULE] Added automatically production resource constraints\n");
     if ($jobproperties ne ""){
      $jobproperties = "($jobproperties) AND production = \'YES\'"; 
     }else{
      $jobproperties = "production = \'YES\'"; 
     }
    }
---

**Comment by npf** [comment] 2015-07-17 15:03
OK.
I reproduce with Mysql.
For Postgresql, it seems OK.

**Comment by npf** [comment] 2015-07-17 15:19
Bizarre... sounds like the dbh->quote in the IO::update_admission_rule function does not do what is expected, when the db is MySQL...

**Comment by npf** [comment] 2015-07-17 15:23
@bzizou, assigning to you since the code was yours before my last changes :-) (function used by the REST API).
We may look at oaradmin (ruby) to see if something was done to handle the case.

**Closed** 2015-07-29 14:21 UTC
Labels: 2.5, bug, g5k, question
